# -*- coding: utf-8 -*-
"""DatMingUAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XPP3mgZ11NfHntYkqvrJf_X7M0aLj3iT

# **Metode : KNN, Decision Tree, Metode Random Forest, Metode Bagging ,Metode Logistic Regression, Metode Naive Bayes, ADAboost, gradient boosting, catboost, xgboost. Dengan menggunakan SMOTE, Optimasi parameter dan Threshold Prediction**
"""

!pip install catboost
!pip install imbalanced-learn
!pip install openpyxl
!pip install xgboost
!pip install joblib

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split, StratifiedKFold, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (
    RandomForestClassifier,
    BaggingClassifier,
    AdaBoostClassifier,
    GradientBoostingClassifier
)
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    balanced_accuracy_score,
    classification_report
)

from catboost import CatBoostClassifier
from xgboost import XGBClassifier

"""# **Load Data**"""

file_path = "/content/DataSampelCekNutrisiMakananUAS.xlsx"

data = pd.read_excel(file_path)

print("Ukuran Data:", data.shape)
print(data.head())
print(data["Nutrisi"].value_counts())

"""# **PREPROCESSING DATA**"""

target_col = "Nutrisi"

if "NamaMakanan" in data.columns:
    data = data.drop(columns=["NamaMakanan"])

data[target_col] = pd.to_numeric(data[target_col], errors="coerce")
data = data.dropna(subset=[target_col])
data[target_col] = data[target_col].astype(int)

X = data.drop(columns=[target_col])
y = data[target_col]

for col in X.columns:
    X[col] = pd.to_numeric(X[col], errors="coerce")

numeric_features = X.columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            Pipeline(steps=[
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler())
            ]),
            numeric_features
        )
    ]
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)

"""# **Fungsi Metode**"""

def make_bagging():
    try:
        return BaggingClassifier(
            estimator=DecisionTreeClassifier(random_state=123),
            n_estimators=100,
            random_state=123
        )
    except TypeError:
        return BaggingClassifier(
            base_estimator=DecisionTreeClassifier(random_state=123),
            n_estimators=100,
            random_state=123
        )

def make_adaboost():
    try:
        return AdaBoostClassifier(
            estimator=DecisionTreeClassifier(max_depth=1, random_state=123),
            n_estimators=100,
            learning_rate=0.1,
            random_state=123
        )
    except TypeError:
        return AdaBoostClassifier(
            base_estimator=DecisionTreeClassifier(max_depth=1, random_state=123),
            n_estimators=100,
            learning_rate=0.1,
            random_state=123
        )

def get_positive_probability(model, X_data):
    if hasattr(model, "predict_proba"):
        return model.predict_proba(X_data)[:, 1]
    else:
        return model.predict(X_data)

def hitung_metrik(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()

    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "F1_Score": f1_score(y_true, y_pred, zero_division=0),
        "Balanced_Accuracy": balanced_accuracy_score(y_true, y_pred),
        "TN": tn,
        "FP": fp,
        "FN": fn,
        "TP": tp
    }

def cari_threshold_terbaik(model, X_valid, y_valid):
    prob = get_positive_probability(model, X_valid)

    best_threshold = 0.50
    best_score = -1

    for threshold in np.arange(0.10, 0.91, 0.01):
        y_pred = (prob >= threshold).astype(int)
        score = f1_score(y_valid, y_pred, zero_division=0)

        if score > best_score:
            best_score = score
            best_threshold = threshold

    return round(best_threshold, 2), best_score

"""# **Model Awal**"""

models_awal = {
    "KNN": KNeighborsClassifier(),

    "Decision Tree": DecisionTreeClassifier(
        random_state=123
    ),

    "Random Forest": RandomForestClassifier(
        n_estimators=200,
        random_state=123
    ),

    "Bagging": make_bagging(),

    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=123
    ),

    "Naive Bayes": GaussianNB(),

    "AdaBoost": make_adaboost(),

    "Gradient Boosting": GradientBoostingClassifier(
        random_state=123
    ),

    "CatBoost": CatBoostClassifier(
        iterations=300,
        learning_rate=0.05,
        depth=4,
        verbose=0,
        random_state=123
    ),

    "XGBoost": XGBClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=123
    )
}

"""# **Parameter Optimasi Model**"""

param_grids = {
    "KNN": {
        "model__n_neighbors": [3, 5, 7, 9, 11, 15],
        "model__weights": ["uniform", "distance"],
        "model__metric": ["euclidean", "manhattan"]
    },

    "Decision Tree": {
        "model__criterion": ["gini", "entropy"],
        "model__max_depth": [2, 3, 5, 7, 10, None],
        "model__min_samples_split": [2, 5, 10],
        "model__min_samples_leaf": [1, 2, 5]
    },

    "Random Forest": {
        "model__n_estimators": [100, 200, 300],
        "model__max_depth": [3, 5, 7, 10, None],
        "model__min_samples_split": [2, 5, 10],
        "model__min_samples_leaf": [1, 2, 5],
        "model__max_features": ["sqrt", "log2"]
    },

    "Bagging": {
        "model__n_estimators": [50, 100, 200],
        "model__max_samples": [0.6, 0.8, 1.0],
        "model__max_features": [0.6, 0.8, 1.0]
    },

    "Logistic Regression": {
        "model__C": [0.001, 0.01, 0.1, 1, 10, 100],
        "model__solver": ["liblinear", "lbfgs"],
        "model__penalty": ["l2"]
    },

    "Naive Bayes": {
        "model__var_smoothing": np.logspace(-12, -6, 7)
    },

    "AdaBoost": {
        "model__n_estimators": [50, 100, 200, 300],
        "model__learning_rate": [0.01, 0.05, 0.1, 0.5, 1.0]
    },

    "Gradient Boosting": {
        "model__n_estimators": [100, 200, 300],
        "model__learning_rate": [0.01, 0.05, 0.1, 0.2],
        "model__max_depth": [2, 3, 4],
        "model__subsample": [0.7, 0.8, 1.0]
    },

    "CatBoost": {
        "model__iterations": [100, 200, 300],
        "model__learning_rate": [0.01, 0.03, 0.05, 0.1],
        "model__depth": [3, 4, 5, 6],
        "model__l2_leaf_reg": [1, 3, 5, 7]
    },

    "XGBoost": {
        "model__n_estimators": [100, 200, 300],
        "model__learning_rate": [0.01, 0.03, 0.05, 0.1],
        "model__max_depth": [2, 3, 4, 5],
        "model__subsample": [0.7, 0.8, 1.0],
        "model__colsample_bytree": [0.7, 0.8, 1.0]
    }
}

"""# **Split Data**"""

rasio_data = {
    "80_20": 0.20,
    "90_10": 0.10
}

hasil_evaluasi = []
hasil_parameter = []
hasil_threshold = []

for nama_rasio, test_size in rasio_data.items():

    print("\n" + "="*70)
    print(f"PEMBAGIAN DATA {nama_rasio}")
    print("="*70)

    X_train_full, X_test, y_train_full, y_test = train_test_split(
        X,
        y,
        test_size=test_size,
        stratify=y,
        random_state=123
    )

    X_train, X_valid, y_train, y_valid = train_test_split(
        X_train_full,
        y_train_full,
        test_size=0.20,
        stratify=y_train_full,
        random_state=123
    )

    print("Jumlah Data Training :", len(X_train_full))
    print("Jumlah Data Testing  :", len(X_test))
    print("Jumlah Data Validasi :", len(X_valid))

    best_models = {}

    for nama_model, estimator in models_awal.items():

        print("\n" + "-"*60)
        print(f"Model: {nama_model}")
        print("-"*60)

        pipe_awal = Pipeline(steps=[
            ("prep", preprocessor),
            ("model", estimator)
        ])

        pipe_awal.fit(X_train, y_train)
        y_pred_awal = pipe_awal.predict(X_test)

        metrik_awal = hitung_metrik(y_test, y_pred_awal)
        hasil_evaluasi.append({
            "Rasio_Data": nama_rasio,
            "Model": nama_model,
            "Skenario": "Model Awal",
            "Threshold": 0.50,
            **metrik_awal
        })

        pipe_smote = ImbPipeline(steps=[
            ("prep", preprocessor),
            ("smote", SMOTE(random_state=123)),
            ("model", estimator)
        ])
        pipe_smote.fit(X_train, y_train)
        y_pred_smote = pipe_smote.predict(X_test)

        metrik_smote = hitung_metrik(y_test, y_pred_smote)
        hasil_evaluasi.append({
            "Rasio_Data": nama_rasio,
            "Model": nama_model,
            "Skenario": "SMOTE",
            "Threshold": 0.50,
            **metrik_smote
        })

        pipe_tuning = ImbPipeline(steps=[
            ("prep", preprocessor),
            ("smote", SMOTE(random_state=123)),
            ("model", estimator)
        ])

        jumlah_kombinasi = 1
        for values in param_grids[nama_model].values():
            jumlah_kombinasi *= len(values)

        n_iter = min(30, jumlah_kombinasi)

        search = RandomizedSearchCV(
            estimator=pipe_tuning,
            param_distributions=param_grids[nama_model],
            n_iter=n_iter,
            scoring="f1",
            cv=cv,
            n_jobs=-1,
            random_state=123,
            refit=True
        )

        search.fit(X_train, y_train)

        best_model = search.best_estimator_
        best_models[nama_model] = best_model

        y_pred_opt = best_model.predict(X_test)

        metrik_opt = hitung_metrik(y_test, y_pred_opt)
        hasil_evaluasi.append({
            "Rasio_Data": nama_rasio,
            "Model": nama_model,
            "Skenario": "SMOTE + Optimasi Parameter",
            "Threshold": 0.50,
            **metrik_opt
        })

        params_bersih = {
            key.replace("model__", ""): value
            for key, value in search.best_params_.items()
        }

        hasil_parameter.append({
            "Rasio_Data": nama_rasio,
            "Model": nama_model,
            "Parameter_Optimal": params_bersih,
            "Best_CV_F1": search.best_score_
        })

        print("Parameter Optimal:")
        print(params_bersih)

        best_threshold, best_valid_f1 = cari_threshold_terbaik(
            best_model,
            X_valid,
            y_valid
        )

        prob_test = get_positive_probability(best_model, X_test)
        y_pred_threshold = (prob_test >= best_threshold).astype(int)

        metrik_threshold = hitung_metrik(y_test, y_pred_threshold)

        hasil_evaluasi.append({
            "Rasio_Data": nama_rasio,
            "Model": nama_model,
            "Skenario": "SMOTE + Optimasi Parameter + Threshold Prediction",
            "Threshold": best_threshold,
            **metrik_threshold
        })

        hasil_threshold.append({
            "Rasio_Data": nama_rasio,
            "Model": nama_model,
            "Best_Threshold": best_threshold,
            "Best_Valid_F1": best_valid_f1
        })

        print("Threshold Optimal:", best_threshold)

evaluasi_df = pd.DataFrame(hasil_evaluasi)
parameter_df = pd.DataFrame(hasil_parameter)
threshold_df = pd.DataFrame(hasil_threshold)

ranking_df = evaluasi_df.sort_values(
    by=["F1_Score", "Balanced_Accuracy", "Accuracy"],
    ascending=False
).reset_index(drop=True)

print("\nHASIL EVALUASI SEMUA MODEL")
print(evaluasi_df)

print("\nPARAMETER OPTIMAL")
print(parameter_df)

print("\nTHRESHOLD OPTIMAL")
print(threshold_df)

print("\nRANKING MODEL TERBAIK")
print(ranking_df.head(20))

best_row = ranking_df.iloc[0]

print("\nModel Terbaik:")
print(best_row)

"""# **Matrix Confussion**"""

confusion_matrix_df = evaluasi_df[
    [
        "Rasio_Data",
        "Model",
        "Skenario",
        "Threshold",
        "TN",
        "FP",
        "FN",
        "TP"
    ]
].copy()

confusion_matrix_df["Confusion_Matrix"] = confusion_matrix_df.apply(
    lambda row: f"[[{row['TN']}, {row['FP']}], [{row['FN']}, {row['TP']}]]",
    axis=1
)


pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

confusion_matrix_df = evaluasi_df[
    [
        "Rasio_Data",
        "Model",
        "Skenario",
        "Threshold",
        "TN",
        "FP",
        "FN",
        "TP"
    ]
].copy()

confusion_matrix_df["Confusion_Matrix"] = confusion_matrix_df.apply(
    lambda row: f"""
Prediksi
          0      1
Aktual 0  {row['TN']}     {row['FP']}
Aktual 1  {row['FN']}     {row['TP']}
""",
    axis=1
)

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

for rasio in confusion_matrix_df["Rasio_Data"].unique():

    print("\n" + "="*90)
    print(f"CONFUSION MATRIX DATA SPLIT {rasio}")
    print("="*90)

    data_rasio = confusion_matrix_df[
        confusion_matrix_df["Rasio_Data"] == rasio
    ]

    for model in data_rasio["Model"].unique():

        print("\n" + "-"*90)
        print(f"MODEL : {model}")
        print("-"*90)

        data_model = data_rasio[
            data_rasio["Model"] == model
        ]

        for _, row in data_model.iterrows():

            print(f"\nSkenario  : {row['Skenario']}")
            print(f"Threshold : {row['Threshold']}")
            print(row["Confusion_Matrix"])

"""# **Perbandingan dan Pemilihan Model Terbaik**"""

urutan_model = [
    "CatBoost",
    "XGBoost",
    "KNN",
    "Gradient Boosting",
    "AdaBoost",
    "Decision Tree",
    "Random Forest",
    "Bagging",
    "Logistic Regression",
    "Naive Bayes"
]

mapping_skenario = {
    "Model Awal": "Model Awal",
    "SMOTE": "SMOTE",
    "SMOTE + Optimasi Parameter": "Optimasi Parameter",
    "SMOTE + Optimasi Parameter + Threshold Prediction": "Threshold Prediction"
}

evaluasi_tabel = evaluasi_df.copy()
evaluasi_tabel["Skenario_Tabel"] = evaluasi_tabel["Skenario"].map(mapping_skenario)

metrik_evaluasi = [
    "Accuracy",
    "Balanced_Accuracy",
    "Precision",
    "Recall",
    "F1_Score"
]

tabel_ringkasan = {}

for metrik in metrik_evaluasi:

    tabel = evaluasi_tabel.pivot_table(
        index="Model",
        columns="Skenario_Tabel",
        values=metrik,
        aggfunc="mean"
    )

    tabel = tabel.reindex(urutan_model)

    tabel = tabel[
        [
            "Model Awal",
            "SMOTE",
            "Optimasi Parameter",
            "Threshold Prediction"
        ]
    ]

    tabel = tabel.round(4)
    tabel_ringkasan[metrik] = tabel

    print("\n" + "="*80)
    print(f"TABEL {metrik.upper()}")
    print("="*80)
    print(tabel)

for rasio in evaluasi_tabel["Rasio_Data"].unique():

    data_rasio = evaluasi_tabel[
        evaluasi_tabel["Rasio_Data"] == rasio
    ]

    print("\n" + "#"*90)
    print(f"RINGKASAN EVALUASI UNTUK SPLIT {rasio}")
    print("#"*90)

    for metrik in metrik_evaluasi:

        tabel = data_rasio.pivot_table(
            index="Model",
            columns="Skenario_Tabel",
            values=metrik,
            aggfunc="mean"
        )

        tabel = tabel.reindex(urutan_model)

        tabel = tabel[
            [
                "Model Awal",
                "SMOTE",
                "Optimasi Parameter",
                "Threshold Prediction"
            ]
        ]

        tabel = tabel.round(4)

        print("\n" + "="*80)
        print(f"{metrik.upper()} - SPLIT {rasio}")
        print("="*80)
        print(tabel)

urutan_model = [
    "CatBoost",
    "XGBoost",
    "KNN",
    "Gradient Boosting",
    "AdaBoost",
    "Decision Tree",
    "Random Forest",
    "Bagging",
    "Logistic Regression",
    "Naive Bayes"
]

nama_skenario = {
    "Model Awal": "Model Awal",
    "SMOTE": "SMOTE",
    "SMOTE + Optimasi Parameter": "SMOTE + Optimasi Parameter",
    "SMOTE + Optimasi Parameter + Threshold Prediction": "SMOTE + Optimasi + Threshold"
}

evaluasi_tabel = evaluasi_df.copy()
evaluasi_tabel["Skenario"] = evaluasi_tabel["Skenario"].replace(nama_skenario)

metrik_evaluasi = [
    "Accuracy",
    "Precision",
    "Recall",
    "F1_Score",
    "Balanced_Accuracy"
]

tabel_per_metrik = {}

for rasio in evaluasi_tabel["Rasio_Data"].unique():

    data_rasio = evaluasi_tabel[
        evaluasi_tabel["Rasio_Data"] == rasio
    ]

    for metrik in metrik_evaluasi:

        tabel = data_rasio.pivot_table(
            index="Model",
            columns="Skenario",
            values=metrik,
            aggfunc="first"
        )

        tabel = tabel.reindex(urutan_model)
        tabel = tabel.round(4)

        tabel_per_metrik[f"{rasio}_{metrik}"] = tabel

        print("\n" + "="*100)
        print(f"TABEL {metrik.upper()} - SPLIT {rasio}")
        print("="*100)
        print(tabel)

evaluasi_tabel["Ringkasan_Metrik"] = evaluasi_tabel.apply(
    lambda row:
    f"Acc={row['Accuracy']:.4f}; "
    f"BalAcc={row['Balanced_Accuracy']:.4f}; "
    f"Prec={row['Precision']:.4f}; "
    f"Rec={row['Recall']:.4f}; "
    f"F1={row['F1_Score']:.4f}",
    axis=1
)

tabel_ringkasan = {}

for rasio in evaluasi_tabel["Rasio_Data"].unique():

    data_rasio = evaluasi_tabel[
        evaluasi_tabel["Rasio_Data"] == rasio
    ]

    tabel = data_rasio.pivot_table(
        index="Model",
        columns="Skenario",
        values="Ringkasan_Metrik",
        aggfunc="first"
    )

    tabel = tabel.reindex(urutan_model)

    tabel_ringkasan[rasio] = tabel

    print("\n" + "="*120)
    print(f"TABEL RINGKASAN EVALUASI MODEL - SPLIT {rasio}")
    print("="*120)
    print(tabel)

"""# **Pengecekan Over Fitting**"""

hasil_overfitting = []

def evaluasi_overfitting(y_true, y_pred):
    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Balanced_Accuracy": balanced_accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "F1_Score": f1_score(y_true, y_pred, zero_division=0)
    }

for rasio in rasio_data.keys():

    print("\n" + "="*90)
    print(f"PENGECEKAN OVERFITTING SPLIT {rasio}")
    print("="*90)

    for nama_model in best_models.keys():

        model = best_models[nama_model]

        # Prediksi data training
        y_train_pred = model.predict(X_train_full)

        # Prediksi data testing
        y_test_pred = model.predict(X_test)

        train_score = evaluasi_overfitting(y_train_full, y_train_pred)
        test_score = evaluasi_overfitting(y_test, y_test_pred)

        gap_accuracy = train_score["Accuracy"] - test_score["Accuracy"]
        gap_balanced_accuracy = train_score["Balanced_Accuracy"] - test_score["Balanced_Accuracy"]
        gap_f1 = train_score["F1_Score"] - test_score["F1_Score"]

        if gap_f1 > 0.10:
            status = "Overfitting"
        elif gap_f1 < -0.05:
            status = "Underfitting / Tidak Stabil"
        else:
            status = "Tidak Overfitting"

        hasil_overfitting.append({
            "Rasio_Data": rasio,
            "Model": nama_model,
            "Train_Accuracy": train_score["Accuracy"],
            "Test_Accuracy": test_score["Accuracy"],
            "Gap_Accuracy": gap_accuracy,
            "Train_Balanced_Accuracy": train_score["Balanced_Accuracy"],
            "Test_Balanced_Accuracy": test_score["Balanced_Accuracy"],
            "Gap_Balanced_Accuracy": gap_balanced_accuracy,
            "Train_F1": train_score["F1_Score"],
            "Test_F1": test_score["F1_Score"],
            "Gap_F1": gap_f1,
            "Status": status
        })

overfitting_df = pd.DataFrame(hasil_overfitting)

overfitting_df = overfitting_df.round({
    "Train_Accuracy": 4,
    "Test_Accuracy": 4,
    "Gap_Accuracy": 4,
    "Train_Balanced_Accuracy": 4,
    "Test_Balanced_Accuracy": 4,
    "Gap_Balanced_Accuracy": 4,
    "Train_F1": 4,
    "Test_F1": 4,
    "Gap_F1": 4
})

print("\nHASIL PENGECEKAN OVERFITTING")
print(overfitting_df)